Update architecture
akhlebus/GoogleSheetI18n pull request #2
Opened 2021-05-27 09:03 UTC by VolhaAdaska

2021-06-10 13:04 UTC, watby requested changes
BE structure looks good. Please pay attention to FE env changes.

2021-06-10 13:04 UTC, watby commented on GoogleSheetI18n.Api/Startup.cs
> +                corsPolicyBuilder.WithOrigins(Configuration.GetValue<string>("AppSettings:AllowedOriginUrl"))
May we allow all origins please? We're not limited by the demo UI I believe

2021-06-10 13:04 UTC, watby commented on GoogleSheetI18n.Infrastructure/Features/ObjectTreeForLanguage/I18nKeyValueDto.cs
> +
nit: not sure Alex likes these additional empty lines 😄

2021-06-10 13:04 UTC, watby commented on GoogleSheetI18n.UI/src/App.js
> +import { Layout } from './components/Layout';
TBD with Alex: not sure relative paths are better option than absolute ones.
May we leave as-is unless these changes are critically required?

2021-06-10 13:04 UTC, watby commented on GoogleSheetI18n.UI/src/environments/environment.js
> +export const ENVIRONMENT = {
If we introduce environment config/variables, we need a way to build or configure an env-specific version, and it does not seem we can go into prod like that.

Could you please use build-time environment variables as primary:
https://create-react-app.dev/docs/adding-custom-environment-variables/
e.g. https://www.youtube.com/watch?v=KJE4LtAxLEw
or any option from
https://stackoverflow.com/questions/49579028/adding-an-env-file-to-react-project

2021-06-11 09:06 UTC, VolhaAdaska commented on GoogleSheetI18n.Api/Startup.cs
> +                corsPolicyBuilder.WithOrigins(Configuration.GetValue<string>("AppSettings:AllowedOriginUrl"))
I removed AllowedOriginUrl from appSettings and updated cors policy from **WithOrigins** to **AllowAnyOrigin**

2021-06-11 09:08 UTC, VolhaAdaska commented on GoogleSheetI18n.Infrastructure/Features/ObjectTreeForLanguage/I18nKeyValueDto.cs
> +
Removed empty lines in Models, but I will add code styles in the future to avoid this situation

2021-06-11 09:09 UTC, VolhaAdaska commented on GoogleSheetI18n.UI/src/environments/environment.js
> +export const ENVIRONMENT = {
Removed environments folder and use .env. Add REACT_APP_API_URL to .env

2021-06-11 18:40 UTC, VolhaAdaska commented on GoogleSheetI18n.UI/src/App.js
> +import { Layout } from './components/Layout';
used relative paths

2021-06-11 18:40 UTC, merged